# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44c8d4ee5d2df020315acd74780bb38443fd1354bb720b684d7cf34c84db7ac59e169f33087db5ebc66aabf587d54e78b905755ad8796374c963929dd65ac9c1

test:
  secret_key_base: ee05b077d62b36e18d6ccd76c82b5b55e2d32d683e242324e54ac102760ad521afb2fc6c6609060c60e88869e700845bf8e00c8e4a6893ed9e7b2797e9e0a2df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
